### ISSUE TITLE
Idle auto off does not start when powered on not over the website

### ISSUE THREAD

**Issue by mjfuchs71** [jneilliii/OctoPrint-Tasmota#160]
Hi there,
thanks for the great work with the pllugin.
I have a sonoff dual with to printers attached.
When i turn on the printer via webinterface the idle countdown starts an disconnect the printer.
When i turn on the printer via the sonoff or the ioBroker the idle time does not recognize the printer is turned on.

Perhaps there is a function already with the event handler but it's not documented yet. As far as i have read i could not find anything related.

Thanks Matthias

**Comment by jneilliii** [comment]
You are correct, this plugin has no way of triggering the idle timer if it didn't know the device was powered on. That is one benefit of the mqtt implementation. I can however add in some logic with the status polling that if it detects on and the idle timer is not running to start it up.

**Comment by mjfuchs71** [comment]
Thanks for your reply. that would be great ! Thank you...

**Comment by jneilliii** [comment]
I think I may have this issue resolved with the above commit. If you could test the 1.1.0rc2 release and verify that would be great. You can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted. If you are already on that release channel, you should get an update notice once your local cache times out, or if you force a check.

**Comment by mjfuchs71** [comment]
Hi,
sorry, didn't see your message. Just testet. Still not working.
Setup is:
- Sonoff Basic / Sonoff Dual with Tasmota 9.5 flshed.
Greetings Matthias

**Comment by jneilliii** [comment]
Please make sure that you have the status polling option enabled. That's what will detect the change of your sonoff's current state.
